# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          "XinYiSec"
paginate:       5
baseurl:        ""
url:            "https://github.com/bexonp"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Bexon
  url:          https://bexonp.github.io
  email:        bexon@mail.com

# Custom vars
version:        9.9.9
github:
  repo:         https://github.com/bexonp

# Gems
gems:
  - jekyll-paginate
